<%--
Original Author: Wade Eckert
Professor: John Woods
Course: CSD 430 - Server Side Development
Assignment: Module 1.3 - Programming Assignment
Date: June 7, 2026
Description: This JSP page demonstrates a successful installation and configuration of 
Java, Apache Tomcat, and JSP. The page displays static content, a dynamically generated name, 
and the current date and time generated by the server.
--%>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wade's First JSP Page</title>
</head>
<body>

<h1>Wade Eckert's First JSP Page</h1>

<p>
    This page is running through Apache Tomcat and JSP.
</p>

<% String studentName = "Wade Eckert"; %>

<p>
    Student Name: <%= studentName %>
</p>

<p>
    Current Date and Time:
    <%= new java.util.Date() %>
</p>

</body>
</html>
